services:
  project-env:
    image: dvorster/term-deposit-classifier:73544ff
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64