name: term-deposit-classifier
channels:
- conda-forge
- defaults
dependencies:
- python=3.11.14
- numpy=2.3.5
- pandas=2.3.3
- ucimlrepo=0.0.7
- altair=6.0.0
- scikit-learn=1.7.2
- matplotlib=3.10.8
- ipykernel=7.1.0
- scipy=1.16.3
- pyarrow=22.0.0
- pip=25.3
