name: term-deposit-classifier
channels:
- conda-forge
- defaults
dependencies:
- python=3.11.14
- setuptools<81
- numpy<2.0
- pandas=2.3.3
- ucimlrepo=0.0.7
- altair=6.0.0
- scikit-learn=1.7.2
- ipykernel=7.1.0
- scipy=1.16.3
- pyarrow=22.0.0
- pip=25.3
- make=4.4.1
- jupyterlab=4.4.7
- click=8.3.1
- pip:
  - altair_ally==0.1.1
  - deepchecks==0.19.1
  - pandera==0.27.0
  - vegafusion==2.0.3
  - vegafusion-python-embed==1.6.9
  - vl-convert-python==1.8.0
  - matplotlib==3.10.7
  - quarto-cli==1.8.26
